---
- name: Download running config from AOS-CX switch
  hosts: all
  gather_facts: no

  tasks:
    - name: Get running configuration
      arubanetworks.aoscx.aoscx_command:
        commands: ["show running-config"]
      register: running_config

    - name: Print running configuration
      debug:
        var: running_config.stdout[0]
